version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  kvstore:
    build:
      context: .
      dockerfile: Dockerfile.v2
    depends_on:
      - redis
    environment:
      REDIS_CONNECTION: redis:6379
    stdin_open: true     
    tty: true            
    ports:
      - "5000:5000"

volumes:
  redis-data:

