FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["KeyValueStorage.csproj", "./"]
RUN dotnet restore "KeyValueStorage.csproj"

COPY . .

RUN dotnet publish "KeyValueStorage.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "KeyValueStorage.dll"]